# Generated by Django 4.2.3 on 2023-08-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
